---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
  - name: install_docker
    commands:
      - git clone https://github.com/RohitDarekar816/mern-ecommerce.git
      - docker-compose build
      - docker-compose up

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
