---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
  - name: Step 1
    commands:
      - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - name: Step 2
    commands:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Step 3
    commands:
      - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - name: Step 4
    commands:
      - sudo apt-get update
  - name: Step 5
    commands:
      - sudo apt-get install -y docker-ce
  - name: Step 6
    commands:
      - sudo systemctl start docker
  - name: Step 7
    commands:
      - sudo systemctl enable docker
  - name: Step 8
    commands:
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - name: Step 9
    commands:
      - sudo chmod +x /usr/local/bin/docker-compose
  - name: Step 10
    commands:
      - docker-compose --version

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
