---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
  - name: install_docker
    commands:
      - docker --version

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
