---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
  - name: Step 2
    commands:
      - sudo apt install apt-transport-https ca-certificates curl software-properties-common
  - name: Step 3
    commands:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - name: Step 4
    commands:
      - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: Step 5
    commands:
      - sudo apt update
  - name: Step 6
    commands:
      - sudo apt install docker-ce docker-ce-cli containerd.io
  - name: Step 7
    commands:
      - sudo systemctl enable docker
  - name: Step 10
    commands:
      - docker-compose --version

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
