---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
  - name: Update the apt package index
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      filename: docker

  - name: Update the apt package index again
    apt:
      update_cache: yes

  - name: Install Docker and Docker Compose
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: present

  - name: Ensure Docker service is running
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-`uname -s`-`uname -m`
      dest: /usr/local/bin/docker-compose
      mode: "0755"

  - name: Verify Compose installation
    command: docker-compose --version
    register: docker_compose_version

  - name: Print Docker Compose version
    debug:
      msg: "{{ docker_compose_version.stdout }}"
become: true

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
    - main
